import PublicHeader from '@/components/PublicHeader'

const LAST_UPDATED = 'April 14, 2026'

export const metadata = {
  title: 'Legal — Reelsy',
  description: 'Legal information for Reelsy, including terms of service, acceptable use, and disclaimer.',
}

export default function LegalPage() {
  return (
    <div style={{ background: '#0B0F14', minHeight: '100vh', color: '#F4F8FB' }}>
      <PublicHeader />

      {/* Body */}
      <main style={{ maxWidth: 760, margin: '0 auto', padding: '72px 32px 96px' }}>
        <p style={{ fontSize: 11, fontWeight: 700, color: '#4A5C6E', letterSpacing: '0.14em', textTransform: 'uppercase', marginBottom: 12 }}>Legal</p>
        <h1 style={{ fontSize: 'clamp(28px,4vw,42px)', fontWeight: 700, margin: '0 0 8px', lineHeight: 1.15 }}>Legal Information</h1>
        <p style={{ fontSize: 13, color: '#4A5C6E', marginBottom: 56 }}>Last updated: {LAST_UPDATED}</p>

        <Section title="1. Company">
          <p>Reelsy is operated by Reelsy App, an independent software company. References to "Reelsy," "we," "us," or "our" throughout this site refer to Reelsy App and its services.</p>
        </Section>

        <Section title="2. Service Description">
          <p>Reelsy provides an AI-powered creative platform that allows users to generate images, videos, and related media content using third-party AI model providers. The outputs are generated by machine learning models and are provided as-is.</p>
        </Section>

        <Section title="3. Acceptable Use">
          <p>You agree not to use Reelsy to generate or distribute content that:</p>
          <ul>
            <li>Violates any applicable law or regulation</li>
            <li>Infringes on the intellectual property rights of any third party</li>
            <li>Is defamatory, obscene, or harmful to minors</li>
            <li>Depicts real individuals without their consent in a misleading or harmful manner</li>
            <li>Facilitates fraud, phishing, or other deceptive practices</li>
          </ul>
          <p>We reserve the right to suspend or terminate accounts that violate these conditions without prior notice.</p>
        </Section>

        <Section title="4. Intellectual Property">
          <p>The Reelsy platform, including its interface, branding, and underlying technology, is the exclusive property of Reelsy App. You retain ownership of the prompts you submit. Output ownership is subject to the terms of the underlying AI model providers (e.g., OpenAI, Google, Kuaishou) and applicable law in your jurisdiction.</p>
        </Section>

        <Section title="5. Disclaimer of Warranties">
          <p>The service is provided "as is" and "as available" without warranty of any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or that generated content will meet your specific requirements.</p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p>To the fullest extent permitted by law, Reelsy App shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including but not limited to loss of revenue, data, or business opportunities.</p>
        </Section>

        <Section title="7. Governing Law">
          <p>These terms are governed by applicable law. Any disputes shall be resolved through binding arbitration or in the courts of competent jurisdiction, as determined by applicable law.</p>
        </Section>

        <Section title="8. Changes to This Document">
          <p>We may update this legal information from time to time. Continued use of the service after changes are posted constitutes acceptance of the revised terms. Material changes will be communicated via email or an in-app notice.</p>
        </Section>

        <div style={{ marginTop: 56, paddingTop: 32, borderTop: '1px solid #1E2A3A' }}>
          <p style={{ fontSize: 13, color: '#4A5C6E' }}>
            Questions about this page?{' '}
            <a href="mailto:support@reelsy-app.com" style={{ color: '#738295', textDecoration: 'underline', textUnderlineOffset: 3 }}>
              support@reelsy-app.com
            </a>
          </p>
        </div>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 16, fontWeight: 600, color: '#C8D5E0', margin: '0 0 12px' }}>{title}</h2>
      <div style={{ fontSize: 14, color: '#738295', lineHeight: 1.75 }}>
        {children}
      </div>
    </section>
  )
}
